In [1]:
import numpy as np
import pandas as pd

from nbqol import path_to_git_root

dir = path_to_git_root() # automatically makes path to repo directory (wherever you cloned it)

print("Repository directory: ", dir)

Repository directory:  /Users/timothyliu/Documents/Chou-Repo/EV-Resistance-analysis

From my shortlisted genes obtained from KEGG, I now want to validate that they're significant and not noisy genes

In [2]:
upregulated_hits = {
    "AGAP2": "Endocytosis",
    "DNM3": "Endocytosis",
    "F2R": "Endocytosis",
    "HLA-B": "Endocytosis",
    "HSPA1L": "Endocytosis",
    "RET": "Endocytosis",
    "ATP6V0A2": "Lysosome",
    "AGA": "Lysosome",
    "AP3B2": "Lysosome",
    "ATP6AP1": "Lysosome",
    "CTSE": "Lysosome",
    "CTSF": "Lysosome",
    "CTSS": "Lysosome / Apoptosis",
    "ABCB1": "ADC Resistance/ABC-type transporter",
    "TUBA4A": "Apoptosis",
    "ETV1": "MMAE Resistance (up)",
    "KLHL4": "MMAE Resistance (up)",
    "KIAA1549L": "MMAE Resistance (down)",
    "UST": "MMAE Resistance (down)",
    "ANPEP": "EMT",
    "ADAM12": "EMT",
    "COL5A3": "EMT",
    "FZD8": "EMT",
    "IL32": "EMT",
    "IL6": "EMT",
    "MAGEE1": "EMT",
    "PMP22": "EMT",
    "SERPINE2": "EMT"
}

downregulated_hits = {
    "EHD3": "Endocytosis",
    "ASAH1": "Lysosome",
    "PSAPL1": "Lysosome",
    "GJA1": "MMAE Resistance / EMT",
    "PDZK1": "MMAE Resistance (up)",
    "PRR16": "MMAE Resistance (up)",
    "FAP": "EMT",
    "COL5A1": "EMT",
    "SPP1": "EMT",
    "ABCB11": "ABC-type transporter",
    "ABCG1": "ABC-type transporter",
    "GADD45B": "Apoptosis",
    "ACAP3": "Endocytosis",
    "ASAP3": "Endocytosis",
    "ARRB1": "Endocytosis",
    "CHMP4B": "Endocytosis",
    "DAB2": "Endocytosis",
    "EGF": "Endocytosis",
    "FGFR3": "Endocytosis",
    "KIT": "Endocytosis",
    "NEDD4L": "Endocytosis",
    "PLD1": "Endocytosis",
    "PSD": "Endocytosis",
    "AP1S1": "Lysosome",
    "AP1M1": "Lysosome",
    "ATP6V0A4": "Lysosome",
    "CTSA": "Lysosome",
    "CTSB": "Lysosome",
    "CTSD": "Lysosome",
    "CTSZ": "Lysosome",
    "PPT2": "Lysosome",
    "CDH6": "EMT",
    "COL1A2": "EMT",
    "FBLN5": "EMT",
    "IGFBP2": "EMT",
    "LOXL1": "EMT",
    "MFAP5": "EMT",
    "TNC": "EMT",
    "SPOCK1": "EMT / MMAE Resistance (down, J82)",
    "ABCA12": "ABC transporter",
    "CAV1": "ADC resistance",
    "ATF4": "Apoptosis",
    "BBC3": "Apoptosis",
    "ERN1": "Apoptosis",
    "SLC40A1": "MMAE Resistance (up)",
    "ETS1": "MMAE Resistance (down)",
    "MEF2C": "MMAE Resistance (up, T24)",
    "BMPR1B": "MMAE Resistance (down, T24)",
    "BEGAIN": "MMAE Resistance (down, T24)",
    "TNFSF18": "MMAE Resistance (down, T24)",
    "TP53I11": "MMAE Resistance (down, J82)",
}

combined_hits = {**upregulated_hits, **downregulated_hits}

In [3]:
combined_df = pd.read_csv(dir+'/data/combined-lines_summary.csv')
combined_df

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,GeneSymbol,gene_type,line
0,1933.153304,-3.375006,0.083720,-40.312927,0.000000,0.0,F3,protein_coding,RT112
1,7291.676853,5.953054,0.084600,70.367366,0.000000,0.0,TXNIP,protein_coding,RT112
2,1894.517793,-4.164389,0.099914,-41.679786,0.000000,0.0,DHRS9,protein_coding,RT112
3,1409.878109,-4.876914,0.118682,-41.092419,0.000000,0.0,AREG,protein_coding,RT112
4,1662.933358,-3.886193,0.092667,-41.937209,0.000000,0.0,SLC7A11,protein_coding,RT112
...,...,...,...,...,...,...,...,...,...
70294,0.551443,2.235420,2.570989,0.869479,0.384585,NaN,AC009235.4,processed_pseudogene,647V
70295,0.655140,2.705975,2.526949,1.070847,0.284238,NaN,CD24L4,processed_pseudogene,647V
70296,0.924396,1.795591,2.212172,0.811687,0.416971,NaN,RP11-576C2.1,transcribed_processed_pseudogene,647V
70297,4.840799,-0.204752,1.497768,-0.136705,0.891264,NaN,RP11-424G14.1,lincRNA,647V
70298,0.853668,1.236207,2.201980,0.561407,0.574520,NaN,EIF1AY,protein_coding,647V

Check significance of upregulated hits
- p<0.05, log2FC>1

In [4]:
for gene in upregulated_hits.keys():
    count = 0
    
    if gene in combined_df['GeneSymbol'].values:
        # Check RT112
        row = combined_df[(combined_df['GeneSymbol'] == gene) & (combined_df['line'] == 'RT112')]
        if len(row) > 0 and row['padj'].iloc[0] < 0.05 and row['log2FoldChange'].iloc[0] > 1:
            count = count + 1
        
        # Check UMUC1
        row = combined_df[(combined_df['GeneSymbol'] == gene) & (combined_df['line'] == 'UMUC1')]
        if len(row) > 0 and row['padj'].iloc[0] < 0.05 and row['log2FoldChange'].iloc[0] > 1:
            count = count + 1
        
        # Check 647V
        row = combined_df[(combined_df['GeneSymbol'] == gene) & (combined_df['line'] == '647V')]
        if len(row) > 0 and row['padj'].iloc[0] < 0.05 and row['log2FoldChange'].iloc[0] > 1:
            count = count + 1
        
        print(f"{gene}: significant in {count}/3 cell lines")
    else:
        print(f"{gene}: not found in dataframe")
    
    if count < 2:
        #print logFC and padj for each cell line
        print(f"{gene} details:")
        
        for line in ['RT112', 'UMUC1', '647V']:
            row = combined_df[(combined_df['GeneSymbol'] == gene) & (combined_df['line'] == line)]
            if len(row) > 0:
                print(f"  {line}: log2FC = {row['log2FoldChange'].iloc[0]:.3f}, padj = {row['padj'].iloc[0]:.3e}")
            else:
                print(f"  {line}: not found")
        print()

AGAP2: significant in 2/3 cell lines
DNM3: significant in 2/3 cell lines
F2R: significant in 2/3 cell lines
HLA-B: significant in 1/3 cell lines
HLA-B details:
  RT112: log2FC = 0.936, padj = 1.047e-22
  UMUC1: log2FC = 1.912, padj = 1.398e-109
  647V: log2FC = 0.013, padj = 9.817e-01

HSPA1L: significant in 2/3 cell lines
RET: significant in 1/3 cell lines
RET details:
  RT112: log2FC = 5.968, padj = 2.795e-62
  UMUC1: not found
  647V: not found

ATP6V0A2: significant in 0/3 cell lines
ATP6V0A2 details:
  RT112: log2FC = 0.769, padj = 2.350e-16
  UMUC1: log2FC = -0.096, padj = 5.148e-01
  647V: log2FC = 0.100, padj = 9.301e-01

AGA: significant in 1/3 cell lines
AGA details:
  RT112: log2FC = 1.227, padj = 9.431e-22
  UMUC1: log2FC = -0.532, padj = 6.429e-03
  647V: log2FC = -0.299, padj = 8.959e-01

AP3B2: significant in 1/3 cell lines
AP3B2 details:
  RT112: log2FC = 3.869, padj = 1.191e-09
  UMUC1: log2FC = -0.138, padj = 8.965e-01
  647V: log2FC = 1.502, padj = nan

ATP6AP1: significant in 0/3 cell lines
ATP6AP1 details:
  RT112: log2FC = 0.340, padj = 1.258e-06
  UMUC1: log2FC = -0.132, padj = 4.233e-02
  647V: log2FC = 0.735, padj = 7.029e-04

CTSE: significant in 1/3 cell lines
CTSE details:
  RT112: log2FC = 1.569, padj = 8.532e-18
  UMUC1: log2FC = 1.541, padj = 2.912e-01
  647V: not found

CTSF: significant in 2/3 cell lines
CTSS: significant in 1/3 cell lines
CTSS details:
  RT112: log2FC = 0.744, padj = 1.753e-10
  UMUC1: log2FC = 2.005, padj = 1.290e-79
  647V: log2FC = 0.657, padj = 9.051e-01

ABCB1: significant in 1/3 cell lines
ABCB1 details:
  RT112: log2FC = 9.746, padj = 3.433e-20
  UMUC1: not found
  647V: log2FC = 1.885, padj = 3.475e-01

TUBA4A: significant in 2/3 cell lines
ETV1: significant in 1/3 cell lines
ETV1 details:
  RT112: log2FC = 4.489, padj = 2.580e-15
  UMUC1: not found
  647V: log2FC = -0.057, padj = 9.881e-01

KLHL4: significant in 1/3 cell lines
KLHL4 details:
  RT112: not found
  UMUC1: log2FC = 3.759, padj = 1.175e-66
  647V: not found

KIAA1549L: significant in 2/3 cell lines
UST: significant in 3/3 cell lines
ANPEP: significant in 2/3 cell lines
ADAM12: significant in 2/3 cell lines
COL5A3: significant in 2/3 cell lines
FZD8: significant in 2/3 cell lines
IL32: significant in 3/3 cell lines
IL6: significant in 1/3 cell lines
IL6 details:
  RT112: not found
  UMUC1: log2FC = 4.740, padj = 5.425e-13
  647V: log2FC = 0.662, padj = 3.475e-01

MAGEE1: significant in 2/3 cell lines
PMP22: significant in 2/3 cell lines
SERPINE2: significant in 2/3 cell lines

In [10]:
combined_df[combined_df['GeneSymbol'] == 'CHMP4B']

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,GeneSymbol,gene_type,line
1960,8119.159004,-0.623526,0.070095,-8.895491,5.816142e-19,7.131522e-18,CHMP4B,protein_coding,RT112
24938,11363.738466,-0.848918,0.043495,-19.517493,7.797054e-85,4.358143e-83,CHMP4B,protein_coding,UMUC1
50134,644.686626,-0.407851,0.161579,-2.524161,1.159749e-02,1.112135e-01,CHMP4B,protein_coding,647V

In [6]:
combined_df[combined_df['GeneSymbol'] == 'CTSF']

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,GeneSymbol,gene_type,line
1278,260.546616,1.701062,0.155657,10.928282,8.443166e-28,1.587302e-26,CTSF,protein_coding,RT112
29270,242.609487,1.043385,0.185781,5.616196,1.952073e-08,9.601733e-08,CTSF,protein_coding,UMUC1
50643,195.974484,0.856115,0.401296,2.133374,3.289404e-02,2.271790e-01,CTSF,protein_coding,647V

Check significance of downregulated hits
- p<0.05, log2FC < -0.5 (to get more hits)

In [8]:
for gene in downregulated_hits.keys():
    count = 0
    
    if gene in combined_df['GeneSymbol'].values:
        # Check RT112
        row = combined_df[(combined_df['GeneSymbol'] == gene) & (combined_df['line'] == 'RT112')]
        if len(row) > 0 and row['padj'].iloc[0] < 0.05 and row['log2FoldChange'].iloc[0] < -.5:
            count = count + 1
        
        # Check UMUC1
        row = combined_df[(combined_df['GeneSymbol'] == gene) & (combined_df['line'] == 'UMUC1')]
        if len(row) > 0 and row['padj'].iloc[0] < 0.05 and row['log2FoldChange'].iloc[0] < -.5:
            count = count + 1
        
        # Check 647V
        row = combined_df[(combined_df['GeneSymbol'] == gene) & (combined_df['line'] == '647V')]
        if len(row) > 0 and row['padj'].iloc[0] < 0.05 and row['log2FoldChange'].iloc[0] < -.5:
            count = count + 1
        
        print(f"{gene}: significant in {count}/3 cell lines")
    else:
        print(f"{gene}: not found in dataframe")
    
    if count < 2:
        #print logFC and padj for each cell line
        print(f"{gene} details:")
        
        for line in ['RT112', 'UMUC1', '647V']:
            row = combined_df[(combined_df['GeneSymbol'] == gene) & (combined_df['line'] == line)]
            if len(row) > 0:
                print(f"  {line}: log2FC = {row['log2FoldChange'].iloc[0]:.3f}, padj = {row['padj'].iloc[0]:.3e}")
            else:
                print(f"  {line}: not found")
        print()

EHD3: significant in 2/3 cell lines
ASAH1: significant in 1/3 cell lines
ASAH1 details:
  RT112: log2FC = -0.548, padj = 6.959e-13
  UMUC1: log2FC = -0.311, padj = 8.623e-06
  647V: log2FC = 0.341, padj = 6.887e-01

PSAPL1: significant in 2/3 cell lines
GJA1: significant in 2/3 cell lines
PDZK1: significant in 2/3 cell lines
PRR16: significant in 1/3 cell lines
PRR16 details:
  RT112: not found
  UMUC1: log2FC = -2.243, padj = 1.795e-05
  647V: log2FC = 0.768, padj = nan

FAP: significant in 1/3 cell lines
FAP details:
  RT112: not found
  UMUC1: log2FC = -3.947, padj = 2.271e-02
  647V: log2FC = -1.575, padj = 6.039e-01

COL5A1: significant in 2/3 cell lines
SPP1: significant in 2/3 cell lines
ABCB11: significant in 2/3 cell lines
ABCG1: significant in 2/3 cell lines
GADD45B: significant in 2/3 cell lines
ACAP3: significant in 1/3 cell lines
ACAP3 details:
  RT112: log2FC = -0.641, padj = 2.474e-15
  UMUC1: log2FC = 0.061, padj = 6.521e-01
  647V: log2FC = -0.588, padj = 7.914e-01

ASAP3: significant in 2/3 cell lines
ARRB1: significant in 1/3 cell lines
ARRB1 details:
  RT112: log2FC = -0.328, padj = 6.240e-03
  UMUC1: log2FC = -0.759, padj = 4.500e-08
  647V: log2FC = -1.031, padj = 4.880e-01

CHMP4B: significant in 2/3 cell lines
DAB2: significant in 1/3 cell lines
DAB2 details:
  RT112: log2FC = -3.470, padj = 2.870e-15
  UMUC1: log2FC = 0.298, padj = 2.209e-01
  647V: log2FC = 0.328, padj = 8.968e-01

EGF: significant in 1/3 cell lines
EGF details:
  RT112: log2FC = -4.550, padj = 7.113e-07
  UMUC1: log2FC = -0.886, padj = 3.666e-01
  647V: log2FC = 3.865, padj = nan

FGFR3: significant in 2/3 cell lines
KIT: significant in 1/3 cell lines
KIT details:
  RT112: log2FC = -6.463, padj = 1.106e-05
  UMUC1: not found
  647V: log2FC = 2.919, padj = nan

NEDD4L: significant in 2/3 cell lines
PLD1: significant in 1/3 cell lines
PLD1 details:
  RT112: log2FC = -1.114, padj = 9.679e-26
  UMUC1: log2FC = 0.081, padj = 3.996e-01
  647V: log2FC = 0.179, padj = 9.582e-01

PSD: significant in 1/3 cell lines
PSD details:
  RT112: log2FC = -0.238, padj = 7.567e-01
  UMUC1: log2FC = -1.879, padj = 3.830e-04
  647V: log2FC = 2.258, padj = 5.666e-01

AP1S1: significant in 1/3 cell lines
AP1S1 details:
  RT112: log2FC = 0.047, padj = 6.675e-01
  UMUC1: log2FC = -0.782, padj = 2.208e-31
  647V: log2FC = 0.339, padj = 5.807e-01

AP1M1: significant in 1/3 cell lines
AP1M1 details:
  RT112: log2FC = 0.255, padj = 5.763e-03
  UMUC1: log2FC = -0.616, padj = 1.133e-15
  647V: log2FC = -0.699, padj = 7.526e-01

ATP6V0A4: significant in 1/3 cell lines
ATP6V0A4 details:
  RT112: log2FC = -0.003, padj = 9.911e-01
  UMUC1: log2FC = -1.799, padj = 8.256e-05
  647V: log2FC = -0.116, padj = 9.880e-01

CTSA: significant in 1/3 cell lines
CTSA details:
  RT112: log2FC = -0.119, padj = 1.681e-01
  UMUC1: log2FC = -0.825, padj = 4.003e-34
  647V: log2FC = 0.382, padj = 1.786e-01

CTSB: significant in 1/3 cell lines
CTSB details:
  RT112: log2FC = -0.743, padj = 1.309e-28
  UMUC1: log2FC = 0.573, padj = 7.751e-24
  647V: log2FC = -0.007, padj = 9.956e-01

CTSD: significant in 1/3 cell lines
CTSD details:
  RT112: log2FC = -1.051, padj = 4.885e-52
  UMUC1: log2FC = 0.764, padj = 1.366e-44
  647V: log2FC = 0.049, padj = 9.694e-01

CTSZ: significant in 1/3 cell lines
CTSZ details:
  RT112: log2FC = -0.924, padj = 1.422e-34
  UMUC1: log2FC = -0.089, padj = 9.772e-02
  647V: log2FC = 0.095, padj = 8.937e-01

PPT2: significant in 2/3 cell lines
CDH6: significant in 1/3 cell lines
CDH6 details:
  RT112: log2FC = -7.611, padj = 1.194e-08
  UMUC1: not found
  647V: not found

COL1A2: significant in 1/3 cell lines
COL1A2 details:
  RT112: not found
  UMUC1: log2FC = -6.058, padj = 3.508e-04
  647V: not found

FBLN5: significant in 1/3 cell lines
FBLN5 details:
  RT112: log2FC = -3.234, padj = 2.539e-02
  UMUC1: log2FC = -0.564, padj = 6.777e-01
  647V: log2FC = -1.218, padj = nan

IGFBP2: significant in 2/3 cell lines
LOXL1: significant in 2/3 cell lines
MFAP5: significant in 1/3 cell lines
MFAP5 details:
  RT112: not found
  UMUC1: log2FC = -2.204, padj = 8.186e-06
  647V: log2FC = -1.020, padj = 2.049e-01

TNC: significant in 2/3 cell lines
SPOCK1: significant in 2/3 cell lines
ABCA12: significant in 1/3 cell lines
ABCA12 details:
  RT112: log2FC = -1.145, padj = 5.543e-25
  UMUC1: log2FC = -0.541, padj = 1.002e-01
  647V: log2FC = 0.499, padj = 8.164e-01

CAV1: significant in 2/3 cell lines
ATF4: significant in 2/3 cell lines
BBC3: significant in 2/3 cell lines
ERN1: significant in 1/3 cell lines
ERN1 details:
  RT112: log2FC = -1.254, padj = 2.850e-30
  UMUC1: log2FC = 0.078, padj = 6.414e-01
  647V: log2FC = 0.013, padj = 9.966e-01

SLC40A1: significant in 2/3 cell lines
ETS1: significant in 1/3 cell lines
ETS1 details:
  RT112: log2FC = -0.765, padj = 1.476e-15
  UMUC1: log2FC = 0.095, padj = 2.209e-01
  647V: log2FC = -0.777, padj = 1.010e-01

MEF2C: significant in 1/3 cell lines
MEF2C details:
  RT112: log2FC = -2.438, padj = 6.001e-07
  UMUC1: not found
  647V: log2FC = 0.452, padj = nan

BMPR1B: significant in 2/3 cell lines
BEGAIN: significant in 1/3 cell lines
BEGAIN details:
  RT112: log2FC = -2.547, padj = 3.706e-12
  UMUC1: log2FC = -0.260, padj = 7.328e-01
  647V: log2FC = 1.757, padj = nan

TNFSF18: significant in 1/3 cell lines
TNFSF18 details:
  RT112: log2FC = -4.525, padj = 4.793e-05
  UMUC1: log2FC = 1.397, padj = 2.640e-01
  647V: log2FC = -2.992, padj = 8.830e-02

TP53I11: significant in 1/3 cell lines
TP53I11 details:
  RT112: log2FC = -1.929, padj = 9.721e-38
  UMUC1: log2FC = -0.758, padj = 8.313e-01
  647V: not found