In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from nbqol import path_to_git_root

dir = path_to_git_root() # automatically makes path to repo directory (wherever you cloned it)

print("Repository directory: ", dir)

# type(dir)

Repository directory:  /Users/timothyliu/Documents/Chou-Repo/EV-Resistance-analysis

In [ ]:
rp_rr_df = pd.read_csv(dir+'/data/rp_vs_rr/rp_vs_rr_lfcs_summary.txt', sep='\t')

In [ ]:
rp_rr_df

,baseMean,log2FoldChange,lfcSE,pvalue,padj,GeneSymbol,gene_type
ENSG00000117525.13,1933.153304,-3.371088,0.083777,0.000000,0.000000,F3,protein_coding
ENSG00000265972.5,7291.676853,5.950702,0.084651,0.000000,0.000000,TXNIP,protein_coding
ENSG00000073737.16,1894.517793,-4.159758,0.099946,0.000000,0.000000,DHRS9,protein_coding
ENSG00000109321.10,1409.878109,-4.871269,0.118664,0.000000,0.000000,AREG,protein_coding
ENSG00000151012.13,1662.933358,-3.881998,0.092718,0.000000,0.000000,SLC7A11,protein_coding
...,...,...,...,...,...,...,...
ENSG00000215041.9,673.297854,0.000190,0.100564,0.999590,0.999753,NEURL4,protein_coding
ENSG00000225297.1,2.990742,0.000552,0.604188,0.999775,0.999898,RP4-612C19.2,processed_pseudogene
ENSG00000277007.1,4.795836,0.000778,0.579535,0.999902,0.999902,RP11-392O17.2,lincRNA
ENSG00000279636.2,22.054377,0.000676,0.385402,0.999900,0.999902,LINC00216,lincRNA
ENSG00000232412.1,3.765718,0.000751,0.583946,0.999875,0.999902,RP1-315G1.3,lincRNA

In [ ]:
up_ur_df = pd.read_csv(dir+'/data/up_vs_ur/up_vs_ur_lfcs_summary.txt', sep='\t')

In [ ]:
up_ur_df

,baseMean,log2FoldChange,lfcSE,pvalue,padj,GeneSymbol,gene_type
ENSG00000189334.8,7498.789751,-2.335216,0.053240,0.000000,0.000000,S100A14,protein_coding
ENSG00000185630.18,4147.558405,-3.142345,0.073502,0.000000,0.000000,PBX1,protein_coding
ENSG00000143819.12,9536.176009,1.998321,0.048639,0.000000,0.000000,EPHX1,protein_coding
ENSG00000143653.9,6757.812006,-3.355842,0.055428,0.000000,0.000000,SCCPDH,protein_coding
ENSG00000001617.11,3632.633727,-3.132228,0.076805,0.000000,0.000000,SEMA3F,protein_coding
...,...,...,...,...,...,...,...
ENSG00000133983.14,117.519958,0.000746,0.281659,0.999523,0.999691,COX16,protein_coding
ENSG00000174886.12,339.831941,0.000164,0.153745,0.999666,0.999790,NDUFA11,protein_coding
ENSG00000224356.5,2.792314,0.000637,0.660734,0.999829,0.999875,RP11-151A6.4,sense_intronic
ENSG00000277728.1,6.643244,0.001049,0.581025,0.999834,0.999875,RP11-143K11.7,antisense
ENSG00000228363.2,23.286823,0.000931,0.459559,0.999976,0.999976,AC015971.2,antisense